UPDATE SYS.PROPS$ SET VALUE$ = 'AMERICAN' WHERE NAME = 'NLS_LANGUAGE';
UPDATE SYS.PROPS$ SET VALUE$ = 'AMERICAN' WHERE NAME = 'NLS_TERRITORY';
UPDATE SYS.PROPS$ SET VALUE$ = 'KO16MSWIN949' WHERE NAME = 'NLS_CHARACTERSET';